[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --legacy-peer-deps --cache /tmp/npm-cache']

[phases.build]
cmds = ['npx prisma generate']

[start]
cmd = 'npx prisma migrate deploy && npm start'
